services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
